# @package _global_

defaults:
  - humanoid

# Env structure
env:
  _target_: phys_anim.envs.amp.${backbone}.DiscActionHumanoid
  config:
    # Simulation params
    ## Observations
    discriminator_obs_historical_steps: 10 # todo: review
    disable_discriminator: False
    discriminator_obs_size_per_step: ${robot.dof_obs_size}

    ## Motion-related params
    ### Respawn related params
    state_init: Random

# Globally accessible parameters
