# @package _global_

defaults:
  - humanoid

# Env structure
env:
  _target_: phys_anim.envs.deltaaction.deltaaction.DeltaAction
  config:
    # Simulation params
    ## Observations
    discriminator_obs_historical_steps: 10 # todo: review
    disable_discriminator: False
    discriminator_obs_size_per_step: ${eval:13+${robot.dof_obs_size}+${robot.number_of_actions}+3*${robot.num_key_bodies}}

    ## Motion-related params
    ### Respawn related params
    state_init: Start
    mimic_residual_control: False
    max_episode_length: 1000

    ## Observations
    mimic_conditionable_bodies: null

    ## Termination
    enable_height_termination: False

    ## Motion-related params
    mimic_fixed_motion_per_env: False

    ### Respawn related params
    mimic_motion_sampling:
      init_start_prob: 1
      init_random_prob: 0

    mimic_early_termination: null

    mimic_reward_config:
      positive_constant: 0
      tan_norm_reward: False
      relative_kb_pos: False

      unequal_reward_joint_weights: False
      add_rr_to_lr: True
      rt_ignore_height: True
      sum_before_exp: True

      component_weights:
        gr_rew_w: 0.0
        lr_rew_w: 0.55
        gt_rew_w: 0.0 # original 0.0
        rt_rew_w: 0.0 # original 0.0
        rv_rew_w: 0.0
        rav_rew_w: 0.0
        gv_rew_w: 0.1
        gav_rew_w: 0.1
        kb_rew_w: 0.15
        dv_rew_w: 0.15
        rh_rew_w: 0.1
        kbf_rew_w: 0.0
        pow_rew_w: 0.0002

      #- Global translation (gt)
      #- Global rotation (gr)
      #- Root translation (rt)
      #- Root rotation (rr)
      #- Key bodies (kb)
      #- Degrees of freedom velocity (dv)
      component_coefficients:
        gt_rew_c: -1
        rt_rew_c: -30
        rv_rew_c: -0.5
        rav_rew_c: -0.1
        gv_rew_c: -0.01
        gav_rew_c: -0.01
        kb_rew_c: -10
        gr_rew_c: -0.1
        lr_rew_c: -0.2
        dv_rew_c: -0.002
        rh_rew_c: -100
        kbf_rew_c: -0.01

    mimic_dynamic_sampling:
      enabled: False
      sampling_criteria: reward
      bucket_width: 1.0
      min_bucket_weight: 1e-6
      dynamic_weight_pow: 1.0
      dynamic_weight_max: 40
      update_dynamic_weight_epochs: 5

    mimic_reset_track:
      steps_min: 10 # original 10
      steps_max: 600 # original 600
      grace_period: 5
      reset_on_episode_reset: False
      reset_episode_on_reset_track: True

    mimic_target_pose:
      enabled: False
      type: max-coords-future-rel
      with_time: False
      num_future_steps: 1
      num_obs_per_target_pose: ${.base_num_obs_per_target_pose}
      base_num_obs_per_target_pose: ${eval:${.num_obs_per_joint}*${robot.num_bodies}}
      num_obs_per_joint: 18
