initial_motion: /home/damibran/dev/repos/ProtoMotionsFork/phys_anim/data/motions/sword_shield/amp_sword_and_shield_humanoid_walk.npy
learned_models_root: /home/damibran/dev/repos/ProtoMotionsFork/motion_dataset_learning/results
log_dir: /home/damibran/dev/repos/ProtoMotionsFork/results/full_body_tracker/lightning_logs/version_0
min_delta: 0.002
motions_root: /home/damibran/dev/repos/ProtoMotionsFork/phys_anim/data/motions/sword_shield
one_model_max_train_time_minutes: 60
patience: 50
python_path: /home/damibran/anaconda3/envs/ProtoMotionsEnv/bin/python
to_fine_tune_list: []
train_script: /home/damibran/dev/repos/ProtoMotionsFork/phys_anim/train_agent.py
