# @package _global_

defaults:
  - /algo: mimic
  - /env: mimic
  - /opt/disable_discriminator  # Default mimic experiments don't use the discriminator
  - /opt/mimic/mlp/target_pose_obs
  - /opt/mimic/global_tracking
  - /opt/legged_robot
  - /opt/record_motion

algo:
  config:
    num_games: 1

experiment_name: record_motion
