# @package _global_

algo:
  config:
    eval_callbacks:
      export_motion_cb:
        _target_: phys_anim.agents.callbacks.export_motion.ExportMotion
        config:
          record_dir: output/recordings/mimic_mjc_train
          store_poselib: False

env:
  config:
    export_motion: True
    env_num_to_export: 12